version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME:-rss-feed}
      POSTGRES_USER: ${DB_NAME:-app}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - rss-feed-db-data:/var/lib/postgresql/data
    networks:
      - rss-feed-network
    ports:
      - ${DB_PORT:-5432}:5432

volumes:
  rss-feed-db-data:

networks:
  rss-feed-network:
